server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: time-rocket-server
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]
  mustache:
    enabled: true
    charset: UTF-8
    suffix: .html
    check-template-location: true
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/time_rocket_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time-zone: Asia/Seoul
  jwt:
    secret: ${JWT_SECRET_KEY}
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-name: naver
#            client-id: ${NAVER_CLIENT_ID}
#            client-secret: ${NAVER_CLIENT_SECRET}
#            redirect-uri: http://localhost:8081/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            scope: name,email
#          google:
#            client-name: google
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirect-uri: http://localhost:8081/login/oauth2/code/google
#            authorization-grant-type: authorization_code
#            scope: profile,email
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=login
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-name-attribute: sub
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response
decorator:
  datasource:
    p6spy:
      enable-logging: true
